# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 7",
   "iPhone 7 Plus",
   "iPhone SE",
])

languages([
  ["pt", "pt-BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme "Nextcloud 2"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
project "./Loopin.xcodeproj"
